### ISSUE TITLE
Cannot run exporter, database not found (I think?)

### ISSUE THREAD

**Issue by whit-colm** [IdealChain/signal-media-exporter#2]
Whenever I try to run the exporter, both through standard pip and pipenv, I get the same issue:

```
2019-09-22 15:03:06 ██████ __main__[72005] INFO Read sqlcipher key: 0x████████████████████████████████████████████████████████████████
2019-09-22 15:03:06 ██████ __main__[72005] INFO Connected to sql/db.sqlite, reading messages...
Traceback (most recent call last):
  File "export.py", line 193, in <module>
    msgs = get_messages(config, key)
  File "export.py", line 49, in get_messages
    """)
pysqlcipher3.dbapi2.DatabaseError: file is not a database
```
> (Note I have redacted some potentially personal information an replaced it with `█` blocks). 

I am assuming I need to correct the path to the database, but where do I do that?

Thanks!

**Comment by IdealChain** [comment]
Hi!
Your error is probably due to the recent database migration the Signal Desktop client did - from the SQLCipher v3 encryption parameters to the ones from v4.

Please fetch my latest commit and try again!

**Comment by whit-colm** [comment]
That fixed it, thanks!
